basedir: "/git/tool/file_sync/test_scan"
patterns: ["*.txt","*.php"]
replicator:
 bucket1:
  status: "disable"
  url: "s3://s3-eu-west-1.amazonaws.com"
  bucket: "giulio-bk"
  acces_key: "....."
  secret_key: "....."
  replace: ["/git/tool/",""] 
 ec2web:
  status: "enable"
  url: "ec2://web-autodiscovery"
  refresh: 60
  match_ec2: "web-[0-9]+"
  acces_key: "key123"
  secret_key: "secter1234"